// Static reference data — identical on every client, like a country list
// (architecture/domain-model.md §9). Generated from design/pure/list.html;
// extend by editing this file, the prototype is only the visual reference.

export type CategoryColor =
  | 'green'
  | 'blue'
  | 'yellow'
  | 'red'
  | 'purple'
  | 'indigo'
  | 'orange'
  | 'pink'
  | 'ice'
  | 'cyan'

export type ProductCategory = {
  readonly id: string
  readonly name: string
  readonly emoji: string
  readonly color: CategoryColor
}

export type CatalogProduct = {
  readonly id: string
  readonly name: string
  readonly emoji: string
  readonly unit: string
  readonly categoryId: string
  readonly variants?: readonly string[]
}

/** Categories in supermarket-aisle order — also the sort order on the list. */
export const PRODUCT_CATEGORIES: readonly ProductCategory[] = [
  {
    id: 'fruits-vegetables',
    name: 'Obst & Gemüse',
    emoji: '🍎',
    color: 'green',
  },
  { id: 'dairy-cheese', name: 'Milch & Käse', emoji: '🧀', color: 'blue' },
  { id: 'bread-bakery', name: 'Brot & Gebäck', emoji: '🍞', color: 'yellow' },
  { id: 'meat-fish', name: 'Fleisch & Fisch', emoji: '🥩', color: 'red' },
  {
    id: 'ingredients-spices',
    name: 'Zutaten & Gewürze',
    emoji: '🧂',
    color: 'purple',
  },
  { id: 'beverages', name: 'Getränke', emoji: '🥤', color: 'indigo' },
  {
    id: 'breakfast-cereals',
    name: 'Frühstück & Cerealien',
    emoji: '🥣',
    color: 'orange',
  },
  { id: 'sweets-snacks', name: 'Süßes & Snacks', emoji: '🍫', color: 'pink' },
  { id: 'frozen', name: 'Tiefkühl', emoji: '🧊', color: 'ice' },
  {
    id: 'drugstore-household',
    name: 'Drogerie & Haushalt',
    emoji: '🧴',
    color: 'cyan',
  },
]

export const PRODUCT_CATALOG: readonly CatalogProduct[] = [
  {
    id: 'pineapple',
    name: 'Ananas',
    emoji: '🍍',
    unit: 'St',
    categoryId: 'fruits-vegetables',
  },
  {
    id: 'apples',
    name: 'Äpfel',
    emoji: '🍎',
    unit: 'kg',
    categoryId: 'fruits-vegetables',
    variants: [
      'Elstar',
      'Braeburn',
      'Gala',
      'Granny Smith',
      'Pink Lady',
      'Golden Delicious',
      'Jonagold',
    ],
  },
  {
    id: 'avocado',
    name: 'Avocado',
    emoji: '🥑',
    unit: 'St',
    categoryId: 'fruits-vegetables',
  },
  {
    id: 'bananas',
    name: 'Bananen',
    emoji: '🍌',
    unit: 'St',
    categoryId: 'fruits-vegetables',
  },
  {
    id: 'berries',
    name: 'Beeren',
    emoji: '🍓',
    unit: 'Schale',
    categoryId: 'fruits-vegetables',
    variants: [
      'Erdbeeren',
      'Blaubeeren',
      'Himbeeren',
      'Brombeeren',
      'Johannisbeeren',
      'Stachelbeeren',
    ],
  },
  {
    id: 'pears',
    name: 'Birnen',
    emoji: '🍐',
    unit: 'kg',
    categoryId: 'fruits-vegetables',
    variants: ['Conference', 'Williams', 'Abate'],
  },
  {
    id: 'pomegranate',
    name: 'Granatapfel',
    emoji: '🍏',
    unit: 'St',
    categoryId: 'fruits-vegetables',
  },
  {
    id: 'cherries',
    name: 'Kirschen',
    emoji: '🍒',
    unit: 'Schale',
    categoryId: 'fruits-vegetables',
  },
  {
    id: 'kiwi',
    name: 'Kiwi',
    emoji: '🥝',
    unit: 'St',
    categoryId: 'fruits-vegetables',
  },
  {
    id: 'coconut',
    name: 'Kokosnuss',
    emoji: '🥥',
    unit: 'St',
    categoryId: 'fruits-vegetables',
  },
  {
    id: 'mango',
    name: 'Mango',
    emoji: '🥭',
    unit: 'St',
    categoryId: 'fruits-vegetables',
  },
  {
    id: 'melon',
    name: 'Melone',
    emoji: '🍈',
    unit: 'St',
    categoryId: 'fruits-vegetables',
    variants: [
      'Wassermelone',
      'Honigmelone',
      'Galiamelone',
      'Cantaloupemelone',
    ],
  },
  {
    id: 'stone-fruit',
    name: 'Steinobst',
    emoji: '🍑',
    unit: 'kg',
    categoryId: 'fruits-vegetables',
    variants: [
      'Pfirsiche',
      'Nektarinen',
      'Aprikosen',
      'Pflaumen',
      'Mirabellen',
    ],
  },
  {
    id: 'grapes',
    name: 'Trauben',
    emoji: '🍇',
    unit: 'kg',
    categoryId: 'fruits-vegetables',
    variants: ['Weiße kernlos', 'Rote kernlos', 'Weiße', 'Rote'],
  },
  {
    id: 'citrus-fruits',
    name: 'Zitrusfrüchte',
    emoji: '🍊',
    unit: 'St',
    categoryId: 'fruits-vegetables',
    variants: [
      'Orangen',
      'Zitronen',
      'Limetten',
      'Mandarinen',
      'Clementinen',
      'Grapefruit',
      'Blutorangen',
    ],
  },
  {
    id: 'eggplant',
    name: 'Aubergine',
    emoji: '🍆',
    unit: 'St',
    categoryId: 'fruits-vegetables',
  },
  {
    id: 'beans',
    name: 'Bohnen',
    emoji: '🫘',
    unit: '250g',
    categoryId: 'fruits-vegetables',
    variants: ['Grüne Bohnen', 'Kidney-Bohnen', 'Weiße Bohnen'],
  },
  {
    id: 'broccoli',
    name: 'Brokkoli',
    emoji: '🥦',
    unit: 'St',
    categoryId: 'fruits-vegetables',
  },
  {
    id: 'peas',
    name: 'Erbsen',
    emoji: '🫛',
    unit: '250g',
    categoryId: 'fruits-vegetables',
    variants: ['Zuckererbsen', 'Erbsen TK', 'Erbsen frisch'],
  },
  {
    id: 'fennel',
    name: 'Fenchel',
    emoji: '🌱',
    unit: 'St',
    categoryId: 'fruits-vegetables',
  },
  {
    id: 'cucumber',
    name: 'Gurke',
    emoji: '🥒',
    unit: 'St',
    categoryId: 'fruits-vegetables',
    variants: ['Salatgurke', 'Minigurken', 'Schmorgurke'],
  },
  {
    id: 'ginger',
    name: 'Ingwer',
    emoji: '🫚',
    unit: 'St',
    categoryId: 'fruits-vegetables',
  },
  {
    id: 'potatoes',
    name: 'Kartoffeln',
    emoji: '🥔',
    unit: 'kg',
    categoryId: 'fruits-vegetables',
    variants: [
      'Festkochend',
      'Mehligkochend',
      'Vorwiegend festkochend',
      'Drillinge',
      'Süßkartoffeln',
    ],
  },
  {
    id: 'garlic',
    name: 'Knoblauch',
    emoji: '🧄',
    unit: 'Knolle',
    categoryId: 'fruits-vegetables',
  },
  {
    id: 'cabbage',
    name: 'Kohl',
    emoji: '🥬',
    unit: 'St',
    categoryId: 'fruits-vegetables',
    variants: [
      'Rotkohl',
      'Weißkohl',
      'Spitzkohl',
      'Chinakohl',
      'Wirsing',
      'Rosenkohl',
      'Blumenkohl',
      'Kohlrabi',
      'Grünkohl',
    ],
  },
  {
    id: 'pumpkin',
    name: 'Kürbis',
    emoji: '🎃',
    unit: 'St',
    categoryId: 'fruits-vegetables',
    variants: ['Hokkaido', 'Butternut', 'Muskatkürbis', 'Spaghettikürbis'],
  },
  {
    id: 'leek',
    name: 'Lauch',
    emoji: '🏷️',
    unit: 'St',
    categoryId: 'fruits-vegetables',
  },
  {
    id: 'corn',
    name: 'Mais',
    emoji: '🌽',
    unit: 'St',
    categoryId: 'fruits-vegetables',
  },
  {
    id: 'carrots',
    name: 'Möhren',
    emoji: '🥕',
    unit: 'kg',
    categoryId: 'fruits-vegetables',
  },
  {
    id: 'bell-pepper',
    name: 'Paprika',
    emoji: '🫑',
    unit: 'St',
    categoryId: 'fruits-vegetables',
    variants: ['Rot', 'Gelb', 'Grün', 'Orange', 'Spitzpaprika'],
  },
  {
    id: 'mushrooms',
    name: 'Pilze',
    emoji: '🍄',
    unit: '200g',
    categoryId: 'fruits-vegetables',
    variants: [
      'Champignons',
      'Kräuterseitlinge',
      'Austernpilze',
      'Shiitake',
      'Pfifferlinge',
    ],
  },
  {
    id: 'radishes',
    name: 'Radieschen',
    emoji: '🏷️',
    unit: 'Bund',
    categoryId: 'fruits-vegetables',
  },
  {
    id: 'beetroot',
    name: 'Rote Beete',
    emoji: '🏷️',
    unit: 'Bund',
    categoryId: 'fruits-vegetables',
  },
  {
    id: 'lettuce',
    name: 'Salat',
    emoji: '🥗',
    unit: 'St',
    categoryId: 'fruits-vegetables',
    variants: [
      'Kopfsalat',
      'Eisbergsalat',
      'Feldsalat',
      'Rucola',
      'Romana',
      'Lollo Rosso',
      'Batavia',
    ],
  },
  {
    id: 'celery',
    name: 'Sellerie',
    emoji: '🪴',
    unit: 'St',
    categoryId: 'fruits-vegetables',
    variants: ['Knollensellerie', 'Staudensellerie'],
  },
  {
    id: 'asparagus',
    name: 'Spargel',
    emoji: '🏷️',
    unit: 'Bund',
    categoryId: 'fruits-vegetables',
    variants: ['Weißer Spargel', 'Grüner Spargel'],
  },
  {
    id: 'spinach',
    name: 'Spinat',
    emoji: '🍃',
    unit: 'Beutel',
    categoryId: 'fruits-vegetables',
  },
  {
    id: 'tomatoes',
    name: 'Tomaten',
    emoji: '🍅',
    unit: 'kg',
    categoryId: 'fruits-vegetables',
    variants: [
      'Rispentomaten',
      'Cherrytomaten',
      'Roma',
      'Fleischtomaten',
      'Cocktailtomaten',
    ],
  },
  {
    id: 'zucchini',
    name: 'Zucchini',
    emoji: '🏷️',
    unit: 'St',
    categoryId: 'fruits-vegetables',
  },
  {
    id: 'onions',
    name: 'Zwiebeln',
    emoji: '🧅',
    unit: 'Netz',
    categoryId: 'fruits-vegetables',
    variants: [
      'Gelbe Zwiebeln',
      'Rote Zwiebeln',
      'Schalotten',
      'Frühlingszwiebeln',
    ],
  },
  {
    id: 'herbs',
    name: 'Kräuter',
    emoji: '🌿',
    unit: 'Bund',
    categoryId: 'fruits-vegetables',
    variants: [
      'Basilikum',
      'Petersilie',
      'Schnittlauch',
      'Dill',
      'Koriander',
      'Minze',
      'Rosmarin',
      'Thymian',
      'Oregano',
      'Salbei',
    ],
  },
  {
    id: 'milk',
    name: 'Milch',
    emoji: '🥛',
    unit: 'L',
    categoryId: 'dairy-cheese',
    variants: [
      '1,5% fettarm',
      '3,5% Vollmilch',
      'Laktosefrei',
      'H-Milch',
      'Frischmilch',
    ],
  },
  {
    id: 'butter',
    name: 'Butter',
    emoji: '🧈',
    unit: 'St',
    categoryId: 'dairy-cheese',
    variants: ['Deutsche Markenbutter', 'Irische Butter', 'Sauerrahmbutter'],
  },
  {
    id: 'cheese-slices',
    name: 'Käse Scheiben',
    emoji: '🧀',
    unit: 'Pck',
    categoryId: 'dairy-cheese',
    variants: [
      'Gouda',
      'Emmentaler',
      'Edamer',
      'Butterkäse',
      'Maasdamer',
      'Tilsiter',
    ],
  },
  {
    id: 'cheese-block',
    name: 'Käse Stück',
    emoji: '🧀',
    unit: 'St',
    categoryId: 'dairy-cheese',
    variants: [
      'Parmesan',
      'Gruyère',
      'Cheddar',
      'Brie',
      'Camembert',
      'Mozzarella',
      'Feta',
      'Bergkäse',
    ],
  },
  {
    id: 'cream-cheese',
    name: 'Frischkäse',
    emoji: '🥛',
    unit: 'Becher',
    categoryId: 'dairy-cheese',
    variants: ['Natur', 'Kräuter', 'Philadelphia', 'Doppelrahmstufe'],
  },
  {
    id: 'yogurt',
    name: 'Joghurt',
    emoji: '🥣',
    unit: 'Becher',
    categoryId: 'dairy-cheese',
    variants: [
      'Naturjoghurt',
      'Griechisch',
      'Fruchtjoghurt',
      'Skyr',
      'Trinkjoghurt',
    ],
  },
  {
    id: 'quark',
    name: 'Quark',
    emoji: '🥛',
    unit: 'Becher',
    categoryId: 'dairy-cheese',
    variants: [
      'Magerquark',
      'Speisequark 20%',
      'Speisequark 40%',
      'Kräuterquark',
    ],
  },
  {
    id: 'cream',
    name: 'Sahne',
    emoji: '🥛',
    unit: 'Becher',
    categoryId: 'dairy-cheese',
    variants: [
      'Schlagsahne',
      'Saure Sahne',
      'Crème fraîche',
      'Schmand',
      'Kochsahne',
    ],
  },
  {
    id: 'eggs',
    name: 'Eier',
    emoji: '🥚',
    unit: 'Pck',
    categoryId: 'dairy-cheese',
    variants: ['6er Freiland', '10er Freiland', '6er Bio', '10er Bio'],
  },
  {
    id: 'plant-milk',
    name: 'Pflanzenmilch',
    emoji: '🥛',
    unit: 'L',
    categoryId: 'dairy-cheese',
    variants: [
      'Hafermilch',
      'Sojamilch',
      'Mandelmilch',
      'Kokosmilch',
      'Reismilch',
    ],
  },
  {
    id: 'pudding',
    name: 'Pudding',
    emoji: '🍮',
    unit: 'Becher',
    categoryId: 'dairy-cheese',
    variants: ['Schoko', 'Vanille', 'Griessbrei', 'Milchreis'],
  },
  {
    id: 'margarine',
    name: 'Margarine',
    emoji: '🧈',
    unit: 'Becher',
    categoryId: 'dairy-cheese',
    variants: ['Rama', 'Lätta', 'Becel'],
  },
  {
    id: 'tofu',
    name: 'Tofu',
    emoji: '🧈',
    unit: 'Pck',
    categoryId: 'dairy-cheese',
    variants: ['Natur', 'Geräuchert', 'Seidentofu', 'Mariniert'],
  },
  {
    id: 'bread',
    name: 'Brot',
    emoji: '🍞',
    unit: 'St',
    categoryId: 'bread-bakery',
    variants: [
      'Vollkorn',
      'Mischbrot',
      'Roggenbrot',
      'Dinkel',
      'Weizenbrot',
      'Sauerteig',
      'Pumpernickel',
    ],
  },
  {
    id: 'rolls',
    name: 'Brötchen',
    emoji: '🍞',
    unit: 'St',
    categoryId: 'bread-bakery',
    variants: ['Normal', 'Vollkorn', 'Körnerbrötchen', 'Laugen', 'Ciabatta'],
  },
  {
    id: 'toast',
    name: 'Toast',
    emoji: '🍞',
    unit: 'Pck',
    categoryId: 'bread-bakery',
    variants: ['Weizen', 'Vollkorn', 'Buttermilch', 'Körner'],
  },
  {
    id: 'croissant',
    name: 'Croissant',
    emoji: '🥐',
    unit: 'St',
    categoryId: 'bread-bakery',
  },
  {
    id: 'baguette',
    name: 'Baguette',
    emoji: '🥖',
    unit: 'St',
    categoryId: 'bread-bakery',
  },
  {
    id: 'pretzel',
    name: 'Brezel',
    emoji: '🥨',
    unit: 'St',
    categoryId: 'bread-bakery',
  },
  {
    id: 'cake',
    name: 'Kuchen',
    emoji: '🍰',
    unit: 'St',
    categoryId: 'bread-bakery',
    variants: ['Apfelkuchen', 'Käsekuchen', 'Marmorkuchen', 'Streuselkuchen'],
  },
  {
    id: 'tortillas',
    name: 'Tortillas',
    emoji: '🫓',
    unit: 'Pck',
    categoryId: 'bread-bakery',
    variants: ['Weizen', 'Vollkorn', 'Mais'],
  },
  {
    id: 'crispbread',
    name: 'Knäckebrot',
    emoji: '🍞',
    unit: 'Pck',
    categoryId: 'bread-bakery',
  },
  {
    id: 'flour',
    name: 'Mehl',
    emoji: '🌾',
    unit: 'kg',
    categoryId: 'bread-bakery',
    variants: [
      'Weizenmehl 405',
      'Weizenmehl 550',
      'Dinkelmehl',
      'Vollkornmehl',
    ],
  },
  {
    id: 'chicken',
    name: 'Hähnchen',
    emoji: '🍗',
    unit: 'g',
    categoryId: 'meat-fish',
    variants: ['Brust', 'Schenkel', 'Flügel', 'Ganzes Hähnchen', 'Hackfleisch'],
  },
  {
    id: 'beef',
    name: 'Rind',
    emoji: '🥩',
    unit: 'g',
    categoryId: 'meat-fish',
    variants: ['Hackfleisch', 'Steak', 'Gulasch', 'Rouladen', 'Filet'],
  },
  {
    id: 'pork',
    name: 'Schwein',
    emoji: '🥩',
    unit: 'g',
    categoryId: 'meat-fish',
    variants: [
      'Hackfleisch',
      'Schnitzel',
      'Filet',
      'Kotelett',
      'Gulasch',
      'Bauch',
    ],
  },
  {
    id: 'mixed-ground-meat',
    name: 'Hackfleisch gemischt',
    emoji: '🍖',
    unit: 'g',
    categoryId: 'meat-fish',
  },
  {
    id: 'sausage',
    name: 'Wurst',
    emoji: '🥓',
    unit: 'Pck',
    categoryId: 'meat-fish',
    variants: [
      'Salami',
      'Schinken',
      'Mortadella',
      'Leberwurst',
      'Lyoner',
      'Wiener Würstchen',
    ],
  },
  {
    id: 'bacon',
    name: 'Bacon',
    emoji: '🥓',
    unit: 'Pck',
    categoryId: 'meat-fish',
  },
  {
    id: 'salmon',
    name: 'Lachs',
    emoji: '🦞',
    unit: 'g',
    categoryId: 'meat-fish',
    variants: ['Frisch', 'Räucherlachs', 'TK Filet'],
  },
  {
    id: 'tuna',
    name: 'Thunfisch',
    emoji: '🐟',
    unit: 'Dose',
    categoryId: 'meat-fish',
    variants: ['In Öl', 'In Wasser', 'Im eigenen Saft'],
  },
  {
    id: 'shrimp',
    name: 'Garnelen',
    emoji: '🦐',
    unit: 'g',
    categoryId: 'meat-fish',
    variants: ['Frisch', 'TK', 'Riesengarnelen'],
  },
  {
    id: 'fish-sticks',
    name: 'Fischstäbchen',
    emoji: '🐟',
    unit: 'Pck',
    categoryId: 'meat-fish',
  },
  {
    id: 'trout',
    name: 'Forelle',
    emoji: '🐟',
    unit: 'St',
    categoryId: 'meat-fish',
  },
  {
    id: 'meat-substitute',
    name: 'Fleischersatz',
    emoji: '🌱',
    unit: 'Pck',
    categoryId: 'meat-fish',
    variants: [
      'Beyond Burger',
      'Veganes Hack',
      'Vegane Nuggets',
      'Seitan',
      'Tempeh',
    ],
  },
  {
    id: 'salt',
    name: 'Salz',
    emoji: '🧂',
    unit: 'Pck',
    categoryId: 'ingredients-spices',
  },
  {
    id: 'pepper',
    name: 'Pfeffer',
    emoji: '🏷️',
    unit: 'Pck',
    categoryId: 'ingredients-spices',
  },
  {
    id: 'olive-oil',
    name: 'Olivenöl',
    emoji: '🫒',
    unit: 'Fl',
    categoryId: 'ingredients-spices',
    variants: ['Extra Vergine', 'Zum Braten'],
  },
  {
    id: 'sunflower-oil',
    name: 'Sonnenblumenöl',
    emoji: '🫒',
    unit: 'Fl',
    categoryId: 'ingredients-spices',
  },
  {
    id: 'vinegar',
    name: 'Essig',
    emoji: '🫒',
    unit: 'Fl',
    categoryId: 'ingredients-spices',
    variants: ['Balsamico', 'Weißweinessig', 'Apfelessig'],
  },
  {
    id: 'sugar',
    name: 'Zucker',
    emoji: '🏷️',
    unit: 'kg',
    categoryId: 'ingredients-spices',
    variants: ['Weiß', 'Braun', 'Puderzucker', 'Vanillezucker'],
  },
  {
    id: 'mustard',
    name: 'Senf',
    emoji: '🏷️',
    unit: 'Glas',
    categoryId: 'ingredients-spices',
    variants: ['Mittelscharf', 'Süß', 'Dijon'],
  },
  {
    id: 'ketchup',
    name: 'Ketchup',
    emoji: '🏷️',
    unit: 'Fl',
    categoryId: 'ingredients-spices',
  },
  {
    id: 'mayo',
    name: 'Mayonnaise',
    emoji: '🏷️',
    unit: 'Glas',
    categoryId: 'ingredients-spices',
  },
  {
    id: 'soy-sauce',
    name: 'Sojasauce',
    emoji: '🏷️',
    unit: 'Fl',
    categoryId: 'ingredients-spices',
  },
  {
    id: 'pasta',
    name: 'Nudeln',
    emoji: '🍝',
    unit: 'Pck',
    categoryId: 'ingredients-spices',
    variants: [
      'Spaghetti',
      'Penne',
      'Fusilli',
      'Farfalle',
      'Tagliatelle',
      'Lasagneplatten',
    ],
  },
  {
    id: 'rice',
    name: 'Reis',
    emoji: '🍚',
    unit: 'Pck',
    categoryId: 'ingredients-spices',
    variants: ['Basmati', 'Jasmin', 'Langkorn', 'Risotto', 'Sushi-Reis'],
  },
  {
    id: 'tomato-puree',
    name: 'Passierte Tomaten',
    emoji: '🍅',
    unit: 'Pck',
    categoryId: 'ingredients-spices',
  },
  {
    id: 'tomato-paste',
    name: 'Tomatenmark',
    emoji: '🍅',
    unit: 'Tube',
    categoryId: 'ingredients-spices',
  },
  {
    id: 'coconut-milk-can',
    name: 'Kokosmilch',
    emoji: '🥥',
    unit: 'Dose',
    categoryId: 'ingredients-spices',
  },
  {
    id: 'broth',
    name: 'Brühe',
    emoji: '🍲',
    unit: 'Glas',
    categoryId: 'ingredients-spices',
    variants: ['Gemüse', 'Hühner', 'Rinder'],
  },
  {
    id: 'spices',
    name: 'Gewürze',
    emoji: '🏷️',
    unit: 'Pck',
    categoryId: 'ingredients-spices',
    variants: [
      'Paprika',
      'Curry',
      'Kurkuma',
      'Zimt',
      'Muskat',
      'Kreuzkümmel',
      'Chilliflocken',
      'Oregano getr.',
    ],
  },
  {
    id: 'baking-powder',
    name: 'Backpulver',
    emoji: '🏷️',
    unit: 'Pck',
    categoryId: 'ingredients-spices',
  },
  {
    id: 'yeast',
    name: 'Hefe',
    emoji: '🏷️',
    unit: 'Würfel',
    categoryId: 'ingredients-spices',
    variants: ['Frische Hefe', 'Trockenhefe'],
  },
  {
    id: 'nuts',
    name: 'Nüsse',
    emoji: '🥜',
    unit: 'Pck',
    categoryId: 'ingredients-spices',
    variants: [
      'Walnüsse',
      'Mandeln',
      'Haselnüsse',
      'Cashews',
      'Erdnüsse',
      'Pinienkerne',
    ],
  },
  {
    id: 'breadcrumbs',
    name: 'Paniermehl',
    emoji: '🍞',
    unit: 'Pck',
    categoryId: 'ingredients-spices',
  },
  {
    id: 'oatmeal',
    name: 'Haferflocken',
    emoji: '🌾',
    unit: 'Pck',
    categoryId: 'ingredients-spices',
    variants: ['Zart', 'Kernig'],
  },
  {
    id: 'canned-corn',
    name: 'Mais (Dose)',
    emoji: '🌽',
    unit: 'Dose',
    categoryId: 'ingredients-spices',
  },
  {
    id: 'canned-beans',
    name: 'Bohnen (Dose)',
    emoji: '🫘',
    unit: 'Dose',
    categoryId: 'ingredients-spices',
    variants: ['Kidneybohnen', 'Kichererbsen', 'Weiße Bohnen'],
  },
  {
    id: 'lentils',
    name: 'Linsen',
    emoji: '🏷️',
    unit: 'Pck',
    categoryId: 'ingredients-spices',
    variants: ['Rote Linsen', 'Belugalinsen', 'Tellerlinsen'],
  },
  {
    id: 'couscous',
    name: 'Couscous',
    emoji: '🍚',
    unit: 'Pck',
    categoryId: 'ingredients-spices',
  },
  {
    id: 'quinoa',
    name: 'Quinoa',
    emoji: '🌾',
    unit: 'Pck',
    categoryId: 'ingredients-spices',
  },
  {
    id: 'bulgur',
    name: 'Bulgur',
    emoji: '🌾',
    unit: 'Pck',
    categoryId: 'ingredients-spices',
  },
  {
    id: 'asian-noodles',
    name: 'Asia-Nudeln',
    emoji: '🍜',
    unit: 'Pck',
    categoryId: 'ingredients-spices',
    variants: ['Glasnudeln', 'Reisnudeln', 'Udon', 'Mie-Nudeln'],
  },
  {
    id: 'tortellini',
    name: 'Tortellini',
    emoji: '🥟',
    unit: 'Pck',
    categoryId: 'ingredients-spices',
    variants: ['Käse', 'Fleisch', 'Spinat'],
  },
  {
    id: 'pesto',
    name: 'Pesto',
    emoji: '🌿',
    unit: 'Glas',
    categoryId: 'ingredients-spices',
    variants: ['Basilikum', 'Rosso', 'Rucola'],
  },
  {
    id: 'canned-tomatoes',
    name: 'Dosentomaten',
    emoji: '🍅',
    unit: 'Dose',
    categoryId: 'ingredients-spices',
    variants: ['Gehackt', 'Ganz', 'Stückig'],
  },
  {
    id: 'olives',
    name: 'Oliven',
    emoji: '🫒',
    unit: 'Glas',
    categoryId: 'ingredients-spices',
    variants: ['Grün', 'Schwarz', 'Kalamata'],
  },
  {
    id: 'pickles',
    name: 'Gewürzgurken',
    emoji: '🥒',
    unit: 'Glas',
    categoryId: 'ingredients-spices',
  },
  {
    id: 'sauerkraut',
    name: 'Sauerkraut',
    emoji: '🥬',
    unit: 'Dose',
    categoryId: 'ingredients-spices',
  },
  {
    id: 'curry-paste',
    name: 'Currypaste',
    emoji: '🍛',
    unit: 'Glas',
    categoryId: 'ingredients-spices',
    variants: ['Rot', 'Gelb', 'Grün'],
  },
  {
    id: 'hot-sauce',
    name: 'Scharfe Sauce',
    emoji: '🌶️',
    unit: 'Fl',
    categoryId: 'ingredients-spices',
    variants: ['Sambal Oelek', 'Sriracha', 'Tabasco', 'Harissa'],
  },
  {
    id: 'bbq-sauce',
    name: 'BBQ Sauce',
    emoji: '🍖',
    unit: 'Fl',
    categoryId: 'ingredients-spices',
  },
  {
    id: 'worcester-sauce',
    name: 'Worcestersauce',
    emoji: '🏷️',
    unit: 'Fl',
    categoryId: 'ingredients-spices',
  },
  {
    id: 'water',
    name: 'Wasser',
    emoji: '💧',
    unit: 'Fl',
    categoryId: 'beverages',
    variants: ['Still', 'Medium', 'Sprudel'],
  },
  {
    id: 'juice',
    name: 'Saft',
    emoji: '🧃',
    unit: 'L',
    categoryId: 'beverages',
    variants: [
      'Apfelsaft',
      'Orangensaft',
      'Multivitamin',
      'Traubensaft',
      'Tomatensaft',
      'Apfelschorle',
    ],
  },
  {
    id: 'softdrinks',
    name: 'Softdrinks',
    emoji: '🥤',
    unit: 'Fl',
    categoryId: 'beverages',
    variants: ['Cola', 'Fanta', 'Sprite', 'Spezi', 'Schwip Schwap'],
  },
  {
    id: 'lemonade',
    name: 'Limonade',
    emoji: '🍋',
    unit: 'Fl',
    categoryId: 'beverages',
    variants: ['Zitrone', 'Bionade', 'Fritz-Limo', 'Almdudler'],
  },
  {
    id: 'iced-tea',
    name: 'Eistee',
    emoji: '🧊',
    unit: 'Fl',
    categoryId: 'beverages',
    variants: ['Pfirsich', 'Zitrone', 'Waldbeere'],
  },
  {
    id: 'energy-drinks',
    name: 'Energydrinks',
    emoji: '⚡',
    unit: 'Dose',
    categoryId: 'beverages',
  },
  {
    id: 'coffee',
    name: 'Kaffee',
    emoji: '☕',
    unit: 'Pck',
    categoryId: 'beverages',
    variants: [
      'Filterkaffee',
      'Espresso Bohnen',
      'Pads',
      'Kapseln',
      'Instant',
      'Ganze Bohne',
    ],
  },
  {
    id: 'tea',
    name: 'Tee',
    emoji: '🍵',
    unit: 'Pck',
    categoryId: 'beverages',
    variants: [
      'Schwarztee',
      'Grüntee',
      'Kräutertee',
      'Früchtetee',
      'Kamille',
      'Pfefferminze',
      'Rooibos',
      'Ingwertee',
    ],
  },
  {
    id: 'cocoa',
    name: 'Kakao',
    emoji: '☕',
    unit: 'Dose',
    categoryId: 'beverages',
    variants: ['Kakaopulver', 'Trinkschokolade', 'Ovomaltine'],
  },
  {
    id: 'beer',
    name: 'Bier',
    emoji: '🍺',
    unit: 'Fl',
    categoryId: 'beverages',
    variants: [
      'Pils',
      'Weizen',
      'Helles',
      'Alkoholfrei',
      'Radler',
      'Kellerbier',
    ],
  },
  {
    id: 'wine',
    name: 'Wein',
    emoji: '🍷',
    unit: 'Fl',
    categoryId: 'beverages',
    variants: ['Rotwein', 'Weißwein', 'Rosé'],
  },
  {
    id: 'sparkling-wine',
    name: 'Sekt & Prosecco',
    emoji: '🥂',
    unit: 'Fl',
    categoryId: 'beverages',
    variants: ['Sekt', 'Prosecco', 'Champagner'],
  },
  {
    id: 'spirits',
    name: 'Spirituosen',
    emoji: '🥃',
    unit: 'Fl',
    categoryId: 'beverages',
    variants: ['Gin', 'Wodka', 'Rum', 'Whisky', 'Likör'],
  },
  {
    id: 'muesli',
    name: 'Müsli',
    emoji: '🥣',
    unit: 'Pck',
    categoryId: 'breakfast-cereals',
    variants: [
      'Früchtemüsli',
      'Schokomüsli',
      'Nussmüsli',
      'Knuspermüsli',
      'Bircher Müsli',
      'Protein Müsli',
    ],
  },
  {
    id: 'cornflakes',
    name: 'Cornflakes',
    emoji: '🥣',
    unit: 'Pck',
    categoryId: 'breakfast-cereals',
    variants: ['Classic', 'Schoko', 'Zimtflakes', 'Smacks', 'Crunchy Nut'],
  },
  {
    id: 'porridge',
    name: 'Porridge',
    emoji: '🥣',
    unit: 'Pck',
    categoryId: 'breakfast-cereals',
    variants: ['Classic', 'Schoko', 'Beeren', 'Apfel-Zimt'],
  },
  {
    id: 'cereal-bars',
    name: 'Riegel',
    emoji: '🍫',
    unit: 'Pck',
    categoryId: 'breakfast-cereals',
    variants: [
      'Müsliriegel',
      'Proteinriegel',
      'Fruchtriegel',
      'Schokoriegel',
      'Haferriegel',
    ],
  },
  {
    id: 'jam',
    name: 'Marmelade',
    emoji: '🍓',
    unit: 'Glas',
    categoryId: 'breakfast-cereals',
    variants: [
      'Erdbeere',
      'Aprikose',
      'Himbeere',
      'Kirsche',
      'Mehrfrucht',
      'Bitterorange',
    ],
  },
  {
    id: 'honey',
    name: 'Honig',
    emoji: '🍯',
    unit: 'Glas',
    categoryId: 'breakfast-cereals',
    variants: ['Blütenhonig', 'Waldhonig', 'Akazienhonig', 'Rapshonig'],
  },
  {
    id: 'chocolate-spread',
    name: 'Nuss-Nougat-Creme',
    emoji: '🍫',
    unit: 'Glas',
    categoryId: 'breakfast-cereals',
    variants: ['Nutella', 'Ovomaltine', 'Nudossi'],
  },
  {
    id: 'peanut-butter',
    name: 'Erdnussbutter',
    emoji: '🥜',
    unit: 'Glas',
    categoryId: 'breakfast-cereals',
    variants: ['Crunchy', 'Creamy'],
  },
  {
    id: 'syrup',
    name: 'Sirup',
    emoji: '🍁',
    unit: 'Fl',
    categoryId: 'breakfast-cereals',
    variants: ['Ahornsirup', 'Agavendicksaft', 'Zuckerrübensirup'],
  },
  {
    id: 'fruit-puree',
    name: 'Fruchtmus',
    emoji: '🍎',
    unit: 'Glas',
    categoryId: 'breakfast-cereals',
    variants: ['Apfelmus', 'Mangomus', 'Birnenmus'],
  },
  {
    id: 'chocolate',
    name: 'Schokolade',
    emoji: '🍫',
    unit: 'Tafel',
    categoryId: 'sweets-snacks',
    variants: [
      'Vollmilch',
      'Zartbitter',
      'Weiß',
      'Nuss',
      'Karamell',
      'Marzipan',
    ],
  },
  {
    id: 'cookies',
    name: 'Kekse',
    emoji: '🍪',
    unit: 'Pck',
    categoryId: 'sweets-snacks',
    variants: [
      'Butterkekse',
      'Schokokekse',
      'Doppelkekse',
      'Haferkekse',
      'Spekulatius',
    ],
  },
  {
    id: 'chips',
    name: 'Chips',
    emoji: '🥔',
    unit: 'Tüte',
    categoryId: 'sweets-snacks',
    variants: ['Paprika', 'Salz', 'Sour Cream', 'Ungarisch', 'Chili'],
  },
  {
    id: 'gummy-bears',
    name: 'Fruchtgummi',
    emoji: '🍬',
    unit: 'Tüte',
    categoryId: 'sweets-snacks',
    variants: ['Goldbären', 'Saure', 'Cola-Fläschchen', 'Lakritz'],
  },
  {
    id: 'ice-cream',
    name: 'Eis',
    emoji: '🍨',
    unit: 'Pck',
    categoryId: 'sweets-snacks',
    variants: ['Vanille', 'Schoko', 'Erdbeere', 'Am Stiel', 'Becher', 'Magnum'],
  },
  {
    id: 'popcorn',
    name: 'Popcorn',
    emoji: '🍿',
    unit: 'Tüte',
    categoryId: 'sweets-snacks',
    variants: ['Süß', 'Salzig', 'Karamell'],
  },
  {
    id: 'salty-snacks',
    name: 'Salzgebäck',
    emoji: '🥨',
    unit: 'Tüte',
    categoryId: 'sweets-snacks',
    variants: ['Salzstangen', 'Mini-Brezeln', 'Cracker', 'Erdnussflips'],
  },
  {
    id: 'wafers',
    name: 'Waffeln',
    emoji: '🧇',
    unit: 'Pck',
    categoryId: 'sweets-snacks',
    variants: ['Schoko-Waffeln', 'Eiswaffeln', 'Stroopwafels'],
  },
  {
    id: 'candy',
    name: 'Bonbons',
    emoji: '🍬',
    unit: 'Tüte',
    categoryId: 'sweets-snacks',
    variants: ['Fruchtbonbons', 'Karamell', 'Husten-Bonbons', 'Toffee'],
  },
  {
    id: 'trail-mix',
    name: 'Studentenfutter',
    emoji: '🥜',
    unit: 'Tüte',
    categoryId: 'sweets-snacks',
  },
  {
    id: 'dried-fruits',
    name: 'Trockenobst',
    emoji: '🍇',
    unit: 'Pck',
    categoryId: 'sweets-snacks',
    variants: ['Rosinen', 'Cranberries', 'Datteln', 'Feigen', 'Aprikosen'],
  },
  {
    id: 'pralines',
    name: 'Pralinen',
    emoji: '🍬',
    unit: 'Pck',
    categoryId: 'sweets-snacks',
    variants: ['Ferrero', 'Merci', 'Lindt', 'Mon Chéri'],
  },
  {
    id: 'frozen-pizza',
    name: 'TK Pizza',
    emoji: '🍕',
    unit: 'Pck',
    categoryId: 'frozen',
    variants: [
      'Margherita',
      'Salami',
      'Spinat',
      'Thunfisch',
      'Hawaii',
      'Vier Käse',
    ],
  },
  {
    id: 'fries',
    name: 'Pommes & Co',
    emoji: '🍟',
    unit: 'Pck',
    categoryId: 'frozen',
    variants: [
      'Pommes Frites',
      'Wedges',
      'Kroketten',
      'Süßkartoffel-Pommes',
      'Rösti',
    ],
  },
  {
    id: 'frozen-vegetables',
    name: 'TK Gemüse',
    emoji: '🥦',
    unit: 'Pck',
    categoryId: 'frozen',
    variants: [
      'Erbsen',
      'Brokkoli',
      'Spinat',
      'Rahmspinat',
      'Mischgemüse',
      'Kaisergemüse',
    ],
  },
  {
    id: 'frozen-fruit',
    name: 'TK Obst',
    emoji: '🍓',
    unit: 'Pck',
    categoryId: 'frozen',
    variants: ['Beeren-Mix', 'Himbeeren', 'Mango', 'Erdbeeren'],
  },
  {
    id: 'frozen-meals',
    name: 'TK Fertiggerichte',
    emoji: '🍲',
    unit: 'Pck',
    categoryId: 'frozen',
    variants: [
      'Lasagne',
      'Schnitzel',
      'Gulasch',
      'Currywurst',
      'Chicken Nuggets',
    ],
  },
  {
    id: 'frozen-rolls',
    name: 'Aufbackbrötchen',
    emoji: '🥐',
    unit: 'Pck',
    categoryId: 'frozen',
    variants: ['Normal', 'Laugenbrötchen', 'Ciabatta'],
  },
  {
    id: 'frozen-fish',
    name: 'TK Fisch',
    emoji: '🐟',
    unit: 'Pck',
    categoryId: 'frozen',
    variants: ['Fischstäbchen', 'Schlemmerfilet', 'Lachsfilet', 'Backfisch'],
  },
  {
    id: 'frozen-herbs',
    name: 'TK Kräuter',
    emoji: '🌿',
    unit: 'Pck',
    categoryId: 'frozen',
    variants: ['8-Kräuter', 'Petersilie', 'Schnittlauch', 'Basilikum'],
  },
  {
    id: 'toilet-paper',
    name: 'Toilettenpapier',
    emoji: '🧻',
    unit: 'Pck',
    categoryId: 'drugstore-household',
  },
  {
    id: 'paper-towels',
    name: 'Küchenpapier',
    emoji: '🧻',
    unit: 'Pck',
    categoryId: 'drugstore-household',
  },
  {
    id: 'dish-soap',
    name: 'Spülmittel',
    emoji: '🧴',
    unit: 'Fl',
    categoryId: 'drugstore-household',
  },
  {
    id: 'laundry-detergent',
    name: 'Waschmittel',
    emoji: '🧴',
    unit: 'Fl',
    categoryId: 'drugstore-household',
    variants: ['Flüssig', 'Pulver', 'Pods/Caps'],
  },
  {
    id: 'fabric-softener',
    name: 'Weichspüler',
    emoji: '🧴',
    unit: 'Fl',
    categoryId: 'drugstore-household',
  },
  {
    id: 'all-purpose-cleaner',
    name: 'Allzweckreiniger',
    emoji: '🧴',
    unit: 'Fl',
    categoryId: 'drugstore-household',
  },
  {
    id: 'trash-bags',
    name: 'Müllbeutel',
    emoji: '🗑️',
    unit: 'Rolle',
    categoryId: 'drugstore-household',
  },
  {
    id: 'aluminum-foil',
    name: 'Alufolie',
    emoji: '🏷️',
    unit: 'Rolle',
    categoryId: 'drugstore-household',
  },
  {
    id: 'cling-wrap',
    name: 'Frischhaltefolie',
    emoji: '🏷️',
    unit: 'Rolle',
    categoryId: 'drugstore-household',
  },
  {
    id: 'sponges',
    name: 'Schwämme',
    emoji: '🧽',
    unit: 'Pck',
    categoryId: 'drugstore-household',
  },
  {
    id: 'toothpaste',
    name: 'Zahnpasta',
    emoji: '🪥',
    unit: 'Tube',
    categoryId: 'drugstore-household',
  },
  {
    id: 'toothbrush',
    name: 'Zahnbürste',
    emoji: '🪥',
    unit: 'St',
    categoryId: 'drugstore-household',
  },
  {
    id: 'shampoo',
    name: 'Shampoo',
    emoji: '🧴',
    unit: 'Fl',
    categoryId: 'drugstore-household',
  },
  {
    id: 'shower-gel',
    name: 'Duschgel',
    emoji: '🚿',
    unit: 'Fl',
    categoryId: 'drugstore-household',
  },
  {
    id: 'hand-soap',
    name: 'Handseife',
    emoji: '🧼',
    unit: 'St',
    categoryId: 'drugstore-household',
  },
  {
    id: 'deodorant',
    name: 'Deo',
    emoji: '🏷️',
    unit: 'St',
    categoryId: 'drugstore-household',
  },
  {
    id: 'tissues',
    name: 'Taschentücher',
    emoji: '🏷️',
    unit: 'Pck',
    categoryId: 'drugstore-household',
  },
  {
    id: 'batteries',
    name: 'Batterien',
    emoji: '🔋',
    unit: 'Pck',
    categoryId: 'drugstore-household',
    variants: ['AA', 'AAA', '9V'],
  },
  {
    id: 'candles',
    name: 'Kerzen',
    emoji: '🕯️',
    unit: 'Pck',
    categoryId: 'drugstore-household',
  },
  {
    id: 'dishwasher-tabs',
    name: 'Spültabs',
    emoji: '🏷️',
    unit: 'Pck',
    categoryId: 'drugstore-household',
  },
]

const catalogById = new Map(
  PRODUCT_CATALOG.map((product) => [product.id, product]),
)

export function findCatalogProduct(productId: string): CatalogProduct | null {
  return catalogById.get(productId) ?? null
}
